/** Transaction Reference Prefixes
 * IAP: In App Payment
 * IAT: In App Transfer
 * AIP: Airtime Purchase
 * DP: Data Purchase
 * BP: Bill Payment
 * TP: Transfer
 * ST: Stash
 * RT: Reversal
 * SP: Shop Purchase
 *
 */

export enum TRANSACTION_SOURCES {
  BANK_TRANSFER = "BANK_TRANSFER",
  USER_TRANSFER = "USER_TRANSFER",
  CARD_DEPOSIT = "CARD_DEPOSIT",
  STORE = "STORE",
  INVOICE = "INVOICE",
  PAYMENT_LINK = "PAYMENT_LINK",
  AVAILABLE_BALANCE = "AVAILABLE_BALANCE",
  LEDGER_BALANCE = "LEDGER_BALANCE",
  RESERVED_BALANCE = "RESERVED_BALANCE",
  STASH = "STASH",
  REVERSAL = "REVERSAL",
}

export enum POST_TYPES {
  T,
}

export enum WS_EVENT {
  CONNECTION = "connection",
  CONNECTED = "connected",
  DISCONNECTED = "disconnect",
  JOIN = "join",

  ORGNIZATION_RESPONSE = "organization_response",
}

export enum GENDER {
  MALE = "male",
  FEMALE = "female",
}

export enum TRANSACTION_TYPES {
  CREDIT = "credit",
  DEBIT = "debit",
}

export enum TRANSACTION_CATEGORIES {
  AIRTIME_PURCHASE = "AIRTIME",
  DATA_PURCHASE = "DATA",
  TV_SUB_PURCHASE = "TV",
  SHOP_PURCHASE = "SHOP",
  IN_APP_PAYMENT = "IN_APP_PAYMENT",
  WITHDRAWAL = "WITHDRAWAL",
  LOAN = "LOAN",
  BILL_PAYMENT = "BILL",
  LOAN_REPAYMENT = "LOAN_REPAYMENT",

  GIFT = "GIFT",
  SCHEDULE_PAYMENT = "SCHEDULE_PAYMENT",
  BULK_SCHEDULE = "BULK_SCHEDULE",
  GROUP_SCHEDULE = "GROUP_SCHEDULE",
  EMPOWERMENT = "EMPOWERMENT",
  AD_REVERSAL = "AD_REVERSAL",
  U_AD_REVERSAL = "U_AD_REVERSAL",
  REFUND = "REFUND",
  SALARY = "SALARY",
  AVAILABLE_TO_LEDGER = "AVAILABLE_TO_LEDGER",
  LEDGER_TO_AVAILABLE = "LEDGER_TO_AVAILABLE",
  CROSS_APP_TRANSFER = "CROSS_APP_TRANSFER",
  CART_PAYMENT = "CART_PAYMENT",
}

export enum SHOP_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export enum PORTFOLIO {
  MEMBER = "MEMBER",
  SPONSOR = "SPONSOR",
  BUSINESS = "BUSINESS",
  HNI = "HNI",
}

export enum ADMIN_ROLE {
  SUPER_ADMIN = "SUPER_ADMIN",
  SUB_ADMIN = "SUB_ADMIN",
  TRANSACTION = "TRANSACTION",
  ENGINEER = "ENGINEER",
  FINANCE = "FINANCE",
  VERIFICATION_REPORT = "VERIFICATION_REPORT",
  SUPPORT = "SUPPORT",
  SOCIALS = "SOCIALS",
  SHOP_SERVICES = "SHOP_SERVICES",
}

export enum PostType {
  IMAGE = "IMAGE",
  TEXT = "TEXT",
  TEXT_IMAGE = "TEXT_IMAGE",
  VIDEO = "VIDEO",
  TEXT_VIDEO = "TEXT_VIDEO",
  TEXT_IMAGE_VIDEO = "TEXT_IMAGE_VIDEO",
  IMAGE_VIDEO = "IMAGE_VIDEO",
}
export enum ContentType {
  BLOG = "BLOG",
  REGULAR = "REGULAR",
  TALENT = "TALENT",
  CONTEST = "CONTEST",
  SURVEY = "SURVEY",
}

export enum TENOR_STATUS {
  OVER_DUE = "OVER_DUE",
  COMPLETED = "COMPLETED",
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
}
export enum STATUS {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  DECLINED = "DECLINED",
  INACTIVE = "INACTIVE",
}

export enum INVOICE_ORDER_STATUS {
  PENDING = "PENDING",
  SHIPPED = "SHIPPED",
  RECEIVED = "RECEIVED",
}

export enum TRANSACTION_STATUS {
  PENDING = "PENDING",
  SUCCESSFUL = "SUCCESSFUL",
  FAILED = "FAILED",
}

export enum CURRENCIES {
  NGN = "NGN",
}

export enum MEANS_OF_ID {
  NIN = "NIN",
  VOTER_ID = "VOTER_ID",
  DRIVERS_LICENSE = "DRIVERS_LICENSE",
  PASSPORT = "PASSPORT",
  OTHER = "OTHER",
}

export enum SKILL_UP_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ENDED = "ENDED",
}

export enum SKILL_UP_ORDER_STATUS {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
}

export enum SCHEDULE {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  BI_WEEKLY = "BI-WEEKLY",
  MONTHLY = "MONTHLY",
  QUARTERLY = "QUARTERLY",
}

export enum SCHEDULE_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  ENDED = "ENDED",
  COMPLETED = "COMPLETED",
}

export enum SERVICE_TYPES {
  MOBILE = "MOBILE",
  WORKSHOP = "WORKSHOP",
  HYBRID = "HYBRID",
  OTHER = "OTHER",
}

export enum MediaType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
}

export enum EMPOWERMENT_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",
}

export enum ARTISAN_HIRE_REQUEST_STATUS {
  PENDING = "PENDING",
  DECLINED = "DECLINED",
  ACCEPTED = "ACCEPTED",
  COMPLETED = "COMPLETED",
}

export enum ACCOUNT_STATUS {
  ACTIVATED = "ACTIVATED",
  DEACTIVATED = "DEACTIVATED",
  PENDING = "PENDING",
}

export enum LOAN_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum WORK_STATUS {
  ACTIVE = "ACTIVE",
  PENDING = "PENDING",
  DECLINED = "DECLINED",
  NO_LONGER_STAFF = "NO_LONGER_STAFF",
}

export enum ELIGIBILITY_STATUS {
  BANNED = "BANNED",
  ELIGIBLE = "ELIGIBLE",
  NOT_ELIGIBLE = "NOT_ELIGIBLE",
  PENDING = "PENDING",
}

export enum CARD_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  EXPIRED = "EXPIRED",
  DELETED = "DELETED",
}

export enum NOTIFIER_TRANSPORT {
  SENDCHAMP = "SENDCHAMP",
  TWILLO = "TWILLO",
}
export enum NOTIFICATION_TYPE {
  TRANSACTION = "TRANSACTION",
  WALLET = "WALLET",
  ACCOUNT = "ACCOUNT",
  UPDATE = "UPDATE",
}

export enum WALLET_MODE {
  STRICT = "STRICT",
  LOOSE = "LOOSE",
}

export enum ADMIN_FUNDING_TYPE {
  SINGLE_USER = "SINGLE_USER",
  BULK = "BULK",
  GROUP = "GROUP",
}

export enum BADGE_REQUEST_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",
}

export enum REPORT_CATEGORY {
  POST = "POST",
  USER = "USER",
  TRANSACTION = "TRANSACTION",
  SHOP = "SHOP",
  PRODUCT = "PRODUCT",
}

export enum REPORT_STATUS {
  PENDING = "PENDING",
  RESOLVED = "RESOLVED",
  REJECTED = "REJECTED",
}

export enum PRODUCT_STATUS {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  DECLINED = "DECLINED",
}

export enum POLL_STATUS {
  PENDING = "PENDING",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  ONGOING = "ONGOING",
}

export enum BVN_STATUS {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  FAILED = "FAILED",
}
export enum NIN_STATUS {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  FAILED = "FAILED",
}

export const WHITE_LIST_ORIGIN: any[] = [
  "http://localhost:3000",
  "https://credx.ng",
  "https://admin.credx.ng",
  "https://hr.credx.ng",
];
